import { GlobalProviders } from './providers'

export const metadata = {
  title: 'Vianna Marinho Advogados',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico'
  }
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
        <GlobalProviders>{children}</GlobalProviders>
      </body>
    </html>
  )
}
